spring:
  application:
    name: monitoring-playground


management:
  metrics:
    export:
      graphite:
        step: 1s
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS